# Generated by Django 2.2.11 on 2020-03-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=300, verbose_name='Tareas Por Realizar')),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
